# Generated by Django 5.0.3 on 2024-03-19 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True, verbose_name='Vehicle Registration Number')),
                ('city_operating', models.CharField(max_length=20, verbose_name='City Operating')),
                ('vehicle_pic', models.ImageField(upload_to='driver/vehicle', verbose_name='Upload Your Vehicle Photo')),
                ('profile_pic', models.ImageField(upload_to='driver/profile_pic', verbose_name='profile_pic')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
