# Generated by Django 5.0.3 on 2024-03-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='city_operating',
            field=models.CharField(max_length=20),
        ),
    ]
