# Generated by Django 5.0.3 on 2024-03-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_drivers_city_operating'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='mobile_number',
            field=models.CharField(default='', max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='driver/profile_pic', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='vehicle_pic',
            field=models.ImageField(blank=True, upload_to='driver/vehicle', verbose_name='Upload Your Vehicle Photo'),
        ),
    ]
