# Generated by Django 5.0.3 on 2024-03-19 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='customer/profile_pic/')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('book_id', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('hours_booked', models.FloatField(verbose_name='Hours Booked')),
                ('journey_start_point', models.CharField(max_length=100, verbose_name='Journey Start Point')),
                ('journey_end_point', models.CharField(max_length=100, verbose_name='Journey End Point')),
                ('payment_amount', models.FloatField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid'), ('refund', 'Refunded')], default='not_paid', max_length=10)),
                ('ride_status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='driver.drivers')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customers')),
            ],
        ),
    ]
