# Generated by Django 5.0.3 on 2024-03-20 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rides_delete_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('6ce9cacd-6d75-4c50-8dad-ead0f7868673'), editable=False, primary_key=True, serialize=False),
        ),
    ]
