# Generated by Django 5.0.3 on 2024-03-20 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_rides_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('95a276cf-b277-4ecd-b007-e056cb0a3cf0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
