# Generated by Django 5.0.3 on 2024-03-20 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_rides_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('c0ac5348-e267-4b60-8161-4c92a9586f4b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rides',
            name='hours_travelled',
            field=models.FloatField(default=0, verbose_name='Hours Travelled'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
