# Generated by Django 5.0.3 on 2024-03-21 04:20

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_rides_book_id_alter_rides_hours_travelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('b1e50339-ef08-4133-b2c6-a6c51cf482b9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rides',
            name='journey_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 4, 20, 57, 714339), verbose_name='Journey End Time'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='journey_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 4, 20, 57, 714319), verbose_name='Journey Start Time'),
        ),
    ]
