# Generated by Django 5.0.3 on 2024-03-21 04:22

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_rides_book_id_alter_rides_journey_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('5ac779d7-f4b0-4ed0-ab45-b22e8022fbae'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rides',
            name='journey_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 4, 22, 21, 869387, tzinfo=datetime.timezone.utc), verbose_name='Journey End Time'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='journey_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 4, 22, 21, 869366, tzinfo=datetime.timezone.utc), verbose_name='Journey Start Time'),
        ),
    ]
