# Generated by Django 5.0.3 on 2024-03-21 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_rides_book_id_alter_rides_journey_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('68c3b8eb-2ef3-45c1-a552-f6868561c87a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rides',
            name='rating',
            field=models.IntegerField(choices=[('poor', 1), ('below average', 2), ('average', 3), ('above average', 4), ('good', 5)], null=True),
        ),
    ]
