# Generated by Django 5.0.3 on 2024-03-21 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_rides_book_id_alter_rides_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('c08ca210-8332-411f-aafa-0b92492d37d3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
