# Generated by Django 5.0.3 on 2024-03-21 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_rides_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('4c4648a3-99a5-469b-a606-160dea1e3ee2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rides',
            name='journey_end_point',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_end_location', to='customer.locations', verbose_name='Journey End Point'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='journey_start_point',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_start_location', to='customer.locations', verbose_name='Journey Start Point'),
        ),
    ]
