# Generated by Django 5.0.3 on 2024-03-21 06:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_rides_book_id_alter_rides_journey_end_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('db5cd9db-415f-4104-bb96-f25a2e9e8b5c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
