# Generated by Django 5.0.3 on 2024-03-21 06:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_rides_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('8807647f-25be-4ec2-9148-310f27a52e60'), editable=False, primary_key=True, serialize=False),
        ),
    ]
