# Generated by Django 5.0.3 on 2024-03-22 16:53

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_rides_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='hours_travelled',
            field=models.FloatField(default=customer.models.generate_travel_hours, verbose_name='Hours Travelled'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='payment_amount',
            field=models.FloatField(default=customer.models.generate_payment_amount),
        ),
    ]
