# Generated by Django 5.0.3 on 2024-03-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_drivers_mobile_number_alter_drivers_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='mobile_number',
            field=models.CharField(default='No Number Found', max_length=20, verbose_name='Mobile Number'),
        ),
    ]
