# Generated by Django 5.0.3 on 2024-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_alter_drivers_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='mobile_number',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
    ]
