# Generated by Django 5.0.3 on 2024-03-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_locations_location_pic'),
        ('driver', '0003_drivers_mobile_number_alter_drivers_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('book_id', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('hours_travelled', models.FloatField(verbose_name='Hours Travelled')),
                ('journey_start_time', models.DateTimeField(verbose_name='Journey Start Time')),
                ('journey_end_time', models.DateTimeField(verbose_name='Journey End Time')),
                ('payment_amount', models.FloatField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid'), ('refund', 'Refunded')], default='not_paid', max_length=10)),
                ('ride_status', models.CharField(choices=[('booked', 'Booked'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[('poor', 1), ('below average', 2), ('average', 3), ('above average', 4), ('good', 5)])),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customers')),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='driver.drivers')),
                ('journey_end_point', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_start_location', to='customer.locations', verbose_name='Journey End Point')),
                ('journey_start_point', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_end_location', to='customer.locations', verbose_name='Journey Start Point')),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
